// ********RoostGPT********
// Test generated by RoostGPT for test cppTest using AI Type  and AI Model 



// ********RoostGPT********
// game_functions.h
#ifndef GAME_FUNCTIONS_H
#define GAME_FUNCTIONS_H

#include <string>
#include <vector>

struct GameState {
    int level;
    int money;
    int exp;
    std::vector<int> inventory;
};

bool processCommand(const std::string& command, GameState& state);
void work(GameState& state);
bool buyItem(const std::string& item, int amount, GameState& state);
void displayStats(const GameState& state);

#endif // GAME_FUNCTIONS_H
